{
 "title": "Payload Tracker",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Payload Tracker API Up",
   "type": "graph",
   "gridPos": { "h": 11, "w": 6, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "up{service=\"payload-tracker-api\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "platform.payload-status Kafka Messages",
   "type": "graph",
   "gridPos": { "h": 11, "w": 9, "x": 6, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(kafka_server_brokertopicmetrics_messagesin_total{topic=\"platform.payload-status\"}[1m])) by (topic)",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Kafka Topic Lag",
   "type": "graph",
   "gridPos": { "h": 11, "w": 9, "x": 15, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_consumergroup_group_topic_sum_lag{topic=\"platform.payload-status\"}",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "API Responses",
   "type": "graph",
   "gridPos": { "h": 13, "w": 10, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(payload_tracker_responses[1m])) by (code)",
     "legendFormat": "{{code}}"
    }
   ]
  },
  {
   "title": "Messages Processed",
   "type": "stat",
   "description": "Successful/failed messages processed metric",
   "gridPos": { "h": 6, "w": 6, "x": 10, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "payload_tracker_messages_processed{container=\"payload-tracker-consumer\"}",
     "legendFormat": "Total {{container}}"
    },
    {
     "expr": "payload_tracker_message_process_errors{container=\"payload-tracker-consumer\"}",
     "legendFormat": "Failed: {{container}}"
    }
   ]
  },
  {
   "title": "API Up (98%)",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(avg_over_time(up{service=\"payload-tracker-api\"}[24h]))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Consumer Up (98%)",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(avg_over_time(up{service=\"payload-tracker-consumer\"}[24h]))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "API Restarts",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(increase(kube_pod_container_status_restarts_total{container=\"payload-tracker-api\"}[$__range]))",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Consumer Restarts",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(increase(kube_pod_container_status_restarts_total{container=\"payload-tracker-consumer\"}[$__range]))",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "API Reponse Counts",
   "type": "stat",
   "description": "Uses time range interval to find average",
   "gridPos": { "h": 12, "w": 6, "x": 10, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum(sum_over_time(payload_tracker_responses[$__interval])) by (code)",
     "legendFormat": "{{code}}"
    }
   ]
  },
  {
   "title": "Consumption Errors (5%)",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(increase(payload_tracker_consumed_messages[$__range])) / sum(increase(payload_tracker_consume_errors[$__range]))"
    }
   ]
  },
  {
   "title": "Invalid Consumer Request Count",
   "type": "stat",
   "gridPos": { "h": 5, "w": 10, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(payload_tracker_consumer_invalid_request_IDs[$__range]))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Percentage of non-5xx (95%)",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(sum_over_time(payload_tracker_responses{code!~\"5.*\"}[$__interval])) / sum(sum_over_time(payload_tracker_responses[$__interval]))"
    }
   ]
  },
  {
   "title": "Database Query Times",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 29 },
   "targets": [
    {
     "expr": "sum(payload_tracker_db_seconds_bucket) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Message Processing Times",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 38 },
   "targets": [
    {
     "expr": "sum(payload_tracker_message_process_seconds_bucket) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  }
 ]
}