#!/bin/bash

./app_common_bash > /tmp/vars.sh
source /tmp/vars.sh

RETENTION_DAYS=${RETENTION_DAYS:-7}
PGPASSWORD=$CLOWDER_DATABASE_PASSWORD psql -h $CLOWDER_DATABASE_HOSTNAME -U $CLOWDER_DATABASE_USERNAME -d $CLOWDER_DATABASE_NAME -c "DELETE FROM payload_statuses WHERE created_at < (NOW() - interval '$RETENTION_DAYS days');"
PGPASSWORD=$CLOWDER_DATABASE_PASSWORD psql -h $CLOWDER_DATABASE_HOSTNAME -U $CLOWDER_DATABASE_USERNAME -d $CLOWDER_DATABASE_NAME -c "DELETE FROM payloads WHERE created_at < (NOW() - interval '$RETENTION_DAYS days');"
PGPASSWORD=$CLOWDER_DATABASE_PASSWORD psql -h $CLOWDER_DATABASE_HOSTNAME -U $CLOWDER_DATABASE_USERNAME -d $CLOWDER_DATABASE_NAME -c "VACUUM ANALYZE payload_statuses;"
PGPASSWORD=$CLOWDER_DATABASE_PASSWORD psql -h $CLOWDER_DATABASE_HOSTNAME -U $CLOWDER_DATABASE_USERNAME -d $CLOWDER_DATABASE_NAME -c "VACUUM ANALYZE payloads;"
PGPASSWORD=$CLOWDER_DATABASE_PASSWORD psql -h $CLOWDER_DATABASE_HOSTNAME -U $CLOWDER_DATABASE_USERNAME -d $CLOWDER_DATABASE_NAME -c "SELECT create_partition(NOW()::DATE + INTERVAL '1 DAY', NOW()::DATE + INTERVAL '2 DAY');"
PGPASSWORD=$CLOWDER_DATABASE_PASSWORD psql -h $CLOWDER_DATABASE_HOSTNAME -U $CLOWDER_DATABASE_USERNAME -d $CLOWDER_DATABASE_NAME -c "SELECT drop_partition(NOW()::DATE - INTERVAL '$RETENTION_DAYS DAY', NOW()::DATE - (($RETENTION_DAYS - 1) || ' DAY')::INTERVAL);"
